[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
actix-web = { version = "4.0", features = ["rustls"] }
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]